# Docker file for the development environment

FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive
RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "iceweasel", "-y"]
RUN ["apt-get", "install", "gedit", "-y"]

RUN export uid=1000 gid=1000 && \
    mkdir -p /home/user && \
    echo "user:x:${uid}:${gid}:user,,,:/home/user:/bin/bash" >> /etc/passwd && \
    echo "user:x:${uid}:" >> /etc/group && \
    chown ${uid}:${gid} -R /home/user
USER user
ENV HOME /home/user

#RUN ["gedit", "/var/www/HTML/BDS/inscr.php"] #Doesn't work anymore
